-       hosts: all
        become: true
        become_method: sudo
        tasks:
        - include: ../tasks/docker-install.yml
        - include: ../tasks/portainer-install.yml
        - include: ../tasks/portainer-conf.yml
