-       name: add GPG key
        apt_key: 
                url: https://download.docker.com/linux/ubuntu/gpg
                state: present
-       name: add repo
        apt_repository: 
                repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' 
                state: present
-       name: update apt cache
        apt: update_cache=yes
-       name: install docker
        package:
                name: docker-ce
                state: latest
